language: cpp
dist: trusty

compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - travis encrypt SOMEVAR="byezogGQKAZB7Df9GNJmDA"

  matrix:
    - ENABLE_UI=OFF
    - ENABLE_UI=ON
      
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
      project:
        name: "chongx1an/aseprite"
        description: "Animated sprite editor & pixel art tool (Windows, macOS, Linux)"
      notification_email: ch0ngx1an@hotmail.com
      build_command_prepend: 
      build_command: "make"
      branch_pattern: travis_test
      
before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_TESTS=ON -DENABLE_UI=$ENABLE_UI
   
script:
  - make
  - |
    if ctest --output-on-failure ; then
      if [[ "$ENABLE_UI" == "OFF" ]]; then
        export ASEPRITE=$PWD/bin/aseprite
        git clone https://github.com/aseprite/tests.git
        cd tests
        bash run-tests.sh
      fi
    fi
    
